series: Welcome to Atlas
title: Getting Started
author:
  name: David Erbelding
  email: daviderbelding@gmail.com
  github: https://github.com/Erbelding
description: Click more for more info.
language:
tags:
  - Core
extra_resources:
  - link: https://github.com/IGME-RIT/Welcome-to-Atlas
    title: Clicking the image (or this link) will bring you to the Github page for this project.
connections:
  - series: Wecome to Atlas
    title: Dummy Text Node
