series: Welcome to Atlas
title: Getting Started
author:
  name: David Erbelding
  email: daviderbelding@gmail.com
  github: https://github.com/Erbelding
description: This example will walk you through the basics of how to use Atlas.
language: 
tags:
extra_resources:
  - link: https://www.visualstudio.com/vs/community/
    title: Download Visual Studio Community Edition
  - link: https://cmake.org/download/
    title: Download CMake
connections:
